mashup/config/routes.rb
Mashup::Application.routes.draw do
  
  resources :startups
  resources :startups do
    member do 
        post 'follow'
        post 'unfollow'
    end
  end

  resources :students
  resources :entrepreneurs
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  root 'logins#home'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/supdatepwd',  to: 'students#updatepwd',            via: 'get'
  match '/eupdatepwd',  to: 'entrepreneurs#updatepwd',            via: 'get'
  match '/sprofile',  to: 'students#profile',            via: 'get'
  match '/sfollowing',  to: 'students#following',            via: 'get'
  match '/allstartups',  to: 'startups#all',            via: 'get'
  match '/allstartups',  to: 'startups#all',            via: 'post'
  match '/allstudents',  to: 'students#all',            via: 'post'
  match '/allstudents',  to: 'students#all',            via: 'get'
  resource :login do
    member do
      get 'callback'
      get 'logout'
    end
  end

  

end

mashup/app/models/startup.rb
class Startup < ActiveRecord::Base
    belongs_to :entrepreneur
    has_many :microposts, dependent: :destroy
    validates :name, presence: true, length: { maximum: 40 }
    validates :about, presence: true
    validates :entrepreneur_id, presence: true
    validates :founderinfo, presence: true
    acts_as_followable              
    has_attached_file :pic, :styles => 
           { :medium => "300x300>", :thumb => "100x100>" }
end

mashup/app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  before_action :signed_in_user,only: [:index,:new,:edit,:update,:destroy,:all,:show]
  before_action :set_startup, only: [:show, :edit, :update, :destroy]
  before_action :user_entrepreneur,only: [:index,:new,:edit,:create,:update,:destroy]
  require 'will_paginate/array'
  # GET /startups
  # GET /startups.json
  def index
    #@startups = Startup.all
    @user = current_user
    @startups = @user.startups.paginate(page: params[:page])
  end

  def all
    #@startups=Startup.paginate(page: params[:page])
    store_location
    @search = Search.new(:startup, params[:search])
    @search.order = 'name'
    @startups = (@search.run).paginate(:page => params[:page], :per_page => 8)
  end
  
  def follow
    store_location
    @startup=Startup.find(params[:id])
    current_user.follow!(@startup)
    redirect_back_or current_user
  end

  def unfollow
    store_location
    @startup=Startup.find(params[:id])
    current_user.unfollow!(@startup)
    redirect_back_or current_user
  end

  # GET /startups/1
  # GET /startups/1.json
  def show
    store_location
    set_startup_id(@startup)
    @microposts = @startup.microposts.paginate(page: params[:page])
    @nmicropost = @startup.microposts.build
  end

  # GET /startups/new
  def new
    @startup = Startup.new
  end

  # GET /startups/1/edit
  def edit
  end

  # POST /startups
  # POST /startups.json
  def create
    @startup = Startup.new(startup_params)
    @startup.entrepreneur_id=current_user.id

    respond_to do |format|
      if @startup.save
        format.html { redirect_to @startup }
        format.json { render action: 'show', status: :created, location: @startup }
        flash[:success] = "Startup was successfully created"
      else
        format.html { render action: 'new' }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /startups/1
  # PATCH/PUT /startups/1.json
  def update
    respond_to do |format|
      if @startup.update(startup_params)
        format.html { redirect_to @startup }
        format.json { head :no_content }
        flash[:success] = "Startup was successfully updated"
      else
        format.html { render action: 'edit' }
        format.json { render json: @startup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /startups/1
  # DELETE /startups/1.json
  def destroy
    @startup.destroy
    respond_to do |format|
      format.html { redirect_to startups_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_startup
      @startup = Startup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def startup_params
      params.require(:startup).permit(:name, :link, :about, :founderinfo, :entrepreneur_id, :pic,:location,:size,:phone,:email,:tagline,:funding)
    end

    

   def user_entrepreneur
      @user = Users.find_by(email: current_user.email)
      if @user.type!="Entrepreneur"
         redirect_to current_user
      end
   end
end

mashup/app/helpers/startups_helper.rb
module StartupsHelper

  def set_startup_id(startup)
      $id=startup.id
  end

  def get_startup_id
      $id
  end

  def correct_startup_user(startup)
       @user = Users.find_by(email: current_user.email)
       if @user.type!="Entrepreneur"
          return false
       else
          if current_user.id==startup.entrepreneur_id
             return true
          else
             return false
          end
       end          
  end
end

mashup/app/views/startups/_form.html.erb
<%= form_for(@startup) do |f| %>
  <% if @startup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@startup.errors.count, "error") %> prohibited this startup from being saved:</h2>

      <ul>
      <% @startup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="field col-md-5">
    <%= f.label :name %><br>
    <%= f.text_field :name,:class=>"form-control" %>
  </div>
</div>
<div class="row">
  <div class="field col-md-5">
    <%= f.label :tagline %><br>
    <%= f.text_field :tagline,:class=>"form-control" %>
  </div>
</div>
<div class="row">
  <div class="field col-md-5">
    <%= f.label :link %><br>
    <%= f.text_field :link,:class=>"form-control" %>
  </div>
</div>
<div class="row">
  <div class="field col-md-5">
    <%= f.label :about %><br>
    <%= f.text_area :about,:class=>"form-control" %>
  </div>
</div>
<div class="row">
  <div class="field col-md-5">
    <%= f.label :founderinfo %><br>
    <%= f.text_area :founderinfo,:class=>"form-control" %>
  </div>
</div>
<div class="row">
  <div class="field col-md-5">
    <%= f.label :funding %><br>
    <%= f.text_field :funding,:class=>"form-control" %>
  </div>
</div>
<div class="row">
  <div class="field col-md-5">
    <%= f.label :location %><br>
    <%= f.text_field :location,:class=>"form-control" %>
  </div>
</div>
<div class="row">
  <div class="field col-md-5">
    <%= f.label :size %><br>
    <%= f.text_field :size,:class=>"form-control" %>
  </div>
</div>
<div class="row">
  <div class="field col-md-5">
    <%= f.label :email %><br>
    <%= f.text_field :email,:class=>"form-control" %>
  </div>
</div>
<div class="row">
  <div class="field col-md-5">
    <%= f.label :phone %><br>
    <%= f.text_field :phone,:class=>"form-control" %>
  </div>
</div>
<p>
     <b> Upload Startup Logo </b>
     <%= f.file_field :pic %>
</p>
  <div class="actions">
    <%= f.submit 'Update Profile',:class=>"btn btn-primary" %>
  </div>
<% end %>

mashup/app/views/startups/_micropost.html.erb
<ul class="list-group">
     <li class="list-group-item">
       <div class="row">
        <div class="col-md-2">
         <a href="#"><img src="img/zomato.png" class="profile_img" ></a>
          
        </div>
        <div class="col-md-8 feed_div ">
         <a href="#" class="feed">
           <p class="feed_news"><%= micropost.content %></p>
         </a>
          
        </div>
        <div class="col-md-2">
         <h6>Posted <%= time_ago_in_words(micropost.created_at) %> ago</h6>
                  
        </div>
         
       </div>
     </li>
    
</ul>

mashup/app/views/startups/all.html.erb
<div class="container">
  <div class="page-header">
  <h4>Startups<small> Look for the best ones</small></h4>
<%= form_for @search, :url => "/allstartups" do |f| %>
  <div class="row">
    <div class="col-md-9">
    <%= f.text_field :name,:class=>"form-control",:placeholder=>"Search by Name" %>
    </div>
   <div class="col-md-2">
     <!-- for the additional search by filter bar ======================================-->
    <div class="panel ">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          Search filters
        </a>
      </h4>
    </div>
    
    </div>
   </div>
    <div class="col-md-1">
      <%= f.submit "Search",:class=>"btn btn-primary" %>
    </div>
   <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
        <div class="col-md-4">
          <%= f.text_field :name,:class=>"form-control",:placeholder=>"Funding" %>
      </div>    
  <div class="col-md-4">
          <%= f.text_field :name,:class=>"form-control",:placeholder=>"Location" %>
      </div>    
  <div class="col-md-4">
          <%= f.text_field :about,:class=>"form-control",:placeholder=>"Product" %>
      </div>
        </div>

      </div>

  </div>
<% end %>
  </div>
  </div>
<div class="container">
    <div class="row demo-tiles">
   <% @startups.each do |startup| %>
        <div class="col-xs-4">
          <div class="tile">
            <% if startup.pic_file_name %>
                <%= image_tag startup.pic.url(:thumb),:class=>"tile-image big-illustration" %>
            <% else %>
                 <%= image_tag  "logo.png",:class=>"tile-image big-illustration" %>
            <% end %>
            <h3 class="tile-title"><%=link_to startup.name,startup %></h3>
            <p><%= startup.tagline %></p>
<% if user_type=="Student" %>
            <% if current_user.follows?(startup) %>
     <%= button_to "Unfollow",{:controller => "startups", :action => "unfollow",:id => startup.id},  :method=>:post,:class=>"btn btn-primary btn-large btn-block" %>
  <% else %>
   <%= button_to 'Follow', {:controller => "startups", :action => "follow",:id => startup.id},  :method=>:post,:class=>"btn btn-primary btn-large btn-block" %>
<% end %>
<% else %>
<%= link_to 'Know More',startup,:class=>"btn btn-primary btn-large btn-block" %>
<% end %>

          </div>
        </div>

<% end %>
        
      </div> <!-- /tiles -->
  </div>
<%= will_paginate @startups %>
</div>

mashup/app/views/startups/edit.html.erb
<h1>Editing startup</h1>


<div class="row">
 <div class="col-md-offset-1">
 <%= render 'form' %>

<%= link_to 'Show', @startup %> |
<%= link_to 'Back', startups_path %>
</div>
</div>

mashup/app/views/startups/index.html.erb
<h1>Listing startups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Link</th>
      <th>About</th>
      <th>Founderinfo</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @startups.each do |startup| %>
      <tr>
        <td><%= startup.name %></td>
        <td><%= startup.link %></td>
        <td><%= startup.about %></td>
        <td><%= startup.founderinfo %></td>
        <td><%= link_to 'Show', startup %></td>
        <td><%= link_to 'Edit', edit_startup_path(startup) %></td>
        <td><%= link_to 'Destroy', startup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
    <%= will_paginate @startups %>
  </tbody>
</table>

<br>

<%= link_to 'New Startup', new_startup_path %>

mashup/app/views/startups/new.html.erb
<div class="container">
    <div class="page-header">
      <h4>New Startup</h4>
    </div>
<%= render 'form' %>

<br>
<%= link_to 'Back', startups_path,:class=>"btn btn-large btn-primary" %>

</div>

mashup/app/views/startups/show.html.erb
<div class="pro-details">
<div class=" ">
  <div align="center">
    <% if @startup.pic_file_name %>
                <%= image_tag @startup.pic.url(:thumb),:class=>"profile-img" %><br><br>
              <% else %>
                 <%= image_tag("logo.png",:class=>"profile-img") %><br><br> 
              <% end %>
    <h2><%= @startup.name %></h2>
    <h6><%= @startup.tagline %></h6>
    <% if user_type=="Student" %>
            <% if current_user.follows?(@startup) %>
     <%= button_to "Unfollow",{:controller => "startups", :action => "unfollow",:id => @startup.id},  :method=>:post,:class=>"btn btn-lg btn-primary" %>
  <% else %>
   <%= button_to 'Follow', {:controller => "startups", :action => "follow",:id => @startup.id},  :method=>:post,:class=>"btn btn-lg btn-primary" %>
<% end %>
<% else %>
<% if correct_startup_user(@startup) %>
                <%= link_to 'Edit Info', edit_startup_path(@startup),:class=>"btn btn-lg btn-primary" %><br>
<% end %>
<% end %>
  </div><br>
  <div class="well">
    <div class="row">
      <div class="col-xs-4">
        <h6>
          About Startup
          
        </h6>
        <hr>
        <div class="">
          <%= @startup.about %>
        </div>
      </div>
      <div class="col-xs-4">
        <h6>
          Founder Info
        </h6>
        <hr>
        <div class="">
          <%= @startup.founderinfo %>
        </div>
      </div>
      <div class="col-xs-4">
        <h6>
          Vitals
        </h6>
        <hr>
        <div class="">
          <p>Location: <a href="#"><%= @startup.location %></a></p>
          <p>Link: <a href="<%= @startup.link %>"><%= @startup.link %></a></p>
          <p>Size: <a href="#"><%= @startup.size %></a></p>
          <p>Funding: <a href="#"><%= @startup.funding %></a></p>
          <p><i class="fa fa-phone"></i>&nbsp<%= @startup.phone %>&nbsp&nbsp&nbsp<i class="fa fa-envelope"></i>&nbsp<%= @startup.email %></p>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<div class="container">
<div class="page-header">
<h4>Live Feed<small>All the latest updates</small></h4>
  </div>
<% if correct_startup_user(@startup) %>
                
                  <%= form_for(@nmicropost) do |f| %>
                            <div class="field col-md-6">
                               <%= f.text_area :content, placeholder: "Compose new micropost...",:class=>"form-control" %>
                            </div>
                            <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %><br><br>
           <% end %>
<% @microposts.each do |micropost| %>
  <div class="row">
    <div class="col-lg-2">
      <a href="#" class="thumbnail d-profile">
      <% if @startup.pic_file_name %>
                <%= image_tag @startup.pic.url(:thumb),:class=>"news-image" %><br><br>
              <% else %>
                 <%= image_tag("logo.png",:class=>"news-image") %><br><br> 
              <% end %>
    </a>
    </div>
    <div class="col-lg-10 ">
      <h6 class="demo-panel-title"><a href="#"><%= @startup.name %></a></h6>
          <div class="share mrl">
            <ul>
              <li>
                <p><%= micropost.content %></p>
              </li>
            <li><small>Posted <%= time_ago_in_words(micropost.created_at) %> ago</small></li>
            </ul>
            
          </div> <!-- /share -->
          
    </div>
   </div>
<% end %>
<%= will_paginate @microposts %>
</div>