mashup/config/routes.rb
Mashup::Application.routes.draw do
  
  resources :startups
  resources :startups do
    member do 
        post 'follow'
        post 'unfollow'
    end
  end

  resources :students
  resources :entrepreneurs
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  root 'logins#home'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/supdatepwd',  to: 'students#updatepwd',            via: 'get'
  match '/eupdatepwd',  to: 'entrepreneurs#updatepwd',            via: 'get'
  match '/sprofile',  to: 'students#profile',            via: 'get'
  match '/sfollowing',  to: 'students#following',            via: 'get'
  match '/allstartups',  to: 'startups#all',            via: 'get'
  match '/allstartups',  to: 'startups#all',            via: 'post'
  match '/allstudents',  to: 'students#all',            via: 'post'
  match '/allstudents',  to: 'students#all',            via: 'get'
  resource :login do
    member do
      get 'callback'
      get 'logout'
    end
  end

  

end

mashup/app/models/student.rb
class Student < ActiveRecord::Base
   before_save { self.email = email.downcase }
   before_create :create_remember_token
   validates :fname, presence: true, length: { maximum: 20 }
   validates :lname, presence: true, length: { maximum: 20 }
   acts_as_follower
   VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
   has_secure_password
   validates :password, length: { minimum: 6 },:confirmation => true, 
                            :if       => :password_changed?
   has_attached_file :pic, :styles => 
          { :medium => "300x300>", :thumb => "100x100>" }

   def Student.new_remember_token
    SecureRandom.urlsafe_base64
   end

   def Student.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
   end

   def password_changed?
    !@password.blank?
   end

  private

   def create_remember_token
     self.remember_token = Student.encrypt(Student.new_remember_token)
   end
end

mashup/app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :signed_in_user, only: [:show, :edit, :update]
  before_action :correct_user,   only: [:edit, :update]
  require 'will_paginate/array'

  def new
   if !current_user
      @user = Student.new
      store_location
   else
      redirect_to current_user
   end
  end

  def profile
     @user = current_user
  end

  def following
     store_location
     @user = current_user
     @startups=@user.followees(Startup).paginate
  end

  def all
    #@students=Student.paginate(page: params[:page])
    @search = Search.new(:student, params[:search])
    @search.order = 'lname'
    @students = (@search.run).paginate(:page => params[:page], :per_page => 9)
  end

  def show
    @user = Student.find(params[:id])
    @microposts = Micropost.paginate(page: params[:page])
  end

  def edit
    $purpose="Edit"
    @user = Student.find(params[:id])
  end

  def updatepwd
    $purpose="Pwd"
    @user = current_user
  end

  def create
    @student = Student.new(user_params)
    if @student.save
      @user=Users.new
      #Handle a successful save.
      if lcurrent_user
         @string=lcurrent_user['siteStandardProfileRequest']['url'].scan(/id=+(\d+)/)[0][0]
         @student.update_attribute(:linkedin_id,@string)
         @user.update_attribute(:linkedin_id,@string)
      end
      @user.update_attribute(:email,@student.email)   
      @user.update_attribute(:type,"Student")
      @user.save
      sign_in(@student,"Student")
      flash[:success] = "Welcome to Mashup!Update your profile for better opportunities"
      redirect_to @student
    else
      @user=@student
      render 'new'
      #redirect_to "/students/new"
    end
  end


  def update
    @user = Student.find(params[:id])
    #params[:student].delete(:password) if params[:student][:password].blank?
    if @user.update_attributes(edit_user_params)
      # Handle a successful update.
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      if $purpose=="Edit"
         render 'edit'
      else
         render 'updatepwd'
      end    
    end
  end

  private

    def user_params
      params.require(:student).permit(:fname, :lname, :email,:password,:password_confirmation)
    end

    def edit_user_params
      params.require(:student).permit(:fname, :lname, :email,:skills,:bio,:google,:fb,:github,:pic,:password,:password_confirmation,:education,:linkedin,:phone)
    end

end

mashup/app/helpers/students_helper.rb
module StudentsHelper

   def correct_student_user
       @temp = Users.find_by(email: current_user.email)
       if @temp.type="Entrepreneur"
          return false
       else
          @student = Student.find(params[:id])
          if @student==current_user
             return true
          else
             return false
          end
       end          
  end
end

mashup/app/views/students/all.html.erb
<div class="container">
    <div class="page-header">
      <h4>People</h4>
<%= form_for @search, :url => "/allstudents" do |f| %>
  <div class="row">
    <div class="col-md-9">
    <%= f.text_field :fname,:class=>"form-control",:placeholder=>"Search by First Name" %>
    </div>
   <div class="col-md-2">
     <!-- for the additional search by filter bar ======================================-->
    <div class="panel ">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          Search filters
        </a>
      </h4>
    </div>
    
    </div>
   </div>
    <div class="col-md-1">
      <%= f.submit "Search",:class=>"btn btn-primary" %>
    </div>
   <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
        <div class="col-md-4">
          <%= f.text_field :fname,:class=>"form-control",:placeholder=>"Education" %>
      </div>    
  <div class="col-md-4">
          <%= f.text_field :skills,:class=>"form-control",:placeholder=>"Skills" %>
      </div>    
  <div class="col-md-4">
          <%= f.text_field :email,:class=>"form-control",:placeholder=>"Email" %>
      </div>
        </div>

      </div>

  </div>
<% end %>
    </div>
</div>
    <div class="container">
      <div class="row demo-tiles">
 <% @students.each do |student| %>
        <div class="col-xs-4">
          <div class="tile">
            <% if student.pic_file_name %>
                <%= image_tag student.pic.url(:thumb),:class=>"tile-image big-illustration" %>
            <% else %>
                 <%= image_tag  "logo.png",:class=>"tile-image big-illustration" %>
            <% end %>
            <h3 class="tile-title"><%= student.fname+" "+student.lname %></h3>
            <p><%= student.skills %></p>
            <%= link_to 'Know More',student,:class=>"btn btn-primary btn-large btn-block" %>
          </div>
        </div>
<% end %>
      </div>
    </div>
<%= will_paginate @students %>
  </div>

mashup/app/views/students/edit.html.erb
<% provide(:title, "Edit user") %>
<div class="container">
    <div class="page-header">
      <h4>Update your Profile</h4>
    </div>

    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :fname,"First Name" %>
      <%= f.text_field :fname,:class=>"form-control" %>
 
      <%= f.label :lname,"Last Name" %>
      <%= f.text_field :lname,:class=>"form-control" %>

      <%= f.label :email %>
      <%= f.text_field :email,:class=>"form-control" %>

      <%= f.label :bio, "About Me" %>
      <%= f.text_area :bio,:class=>"form-control",:placeholder=>"Write about yourself" %>

      <%= f.label :bio, "Education and Experience" %>
      <%= f.text_area :education,:class=>"form-control" %>

      <%= f.label :skills, "My Skills" %>
      <%= f.text_field :skills,:class=>"form-control",:placeholder=>"Your skills seperated by a comma" %>
     
      <%= f.label :bio, "Phone Number" %>
      <%= f.text_field :phone,:class=>"form-control" %>

      
      <%= f.label :pic, "Profile Picture" %>    
      <%= f.file_field :pic %>
 

<h4>Social Media</h4>
      
      <%= f.label :google, "Your Google+ Profile link" %>
      <%= f.text_field :google,:class=>"form-control" %>

      <%= f.label :fb, "Your Facebook Profile link" %>
      <%= f.text_field :fb,:class=>"form-control" %>

      <%= f.label :fb, "Your LinkedIn Profile link" %>
      <%= f.text_field :linkedin,:class=>"form-control" %>
   
      <%= f.label :github, "Your Github/Bitbucket Profile link" %>
      <%= f.text_field :github,:class=>"form-control",:placeholder=>"You can also add a link of your online portfolio" %>   
      <br>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>

</div>

mashup/app/views/students/following.html.erb
<div class="container">
  <div class="page-header">
  <h4>Startups<small> The Ones I like</small></h4>
  </div>
  </div>
<div class="container">
    <div class="row demo-tiles">
   <% @startups.each do |startup| %>
        <div class="col-xs-4">
          <div class="tile">
            <% if startup.pic_file_name %>
                <%= image_tag startup.pic.url(:thumb),:class=>"tile-image big-illustration" %>
            <% else %>
                 <%= image_tag  "logo.png",:class=>"tile-image big-illustration" %>
            <% end %>
            <h3 class="tile-title"><%=link_to startup.name,startup %></h3>
            <p><%= startup.tagline %></p>
<% if user_type=="Student" %>
            <% if current_user.follows?(startup) %>
     <%= button_to "Unfollow",{:controller => "startups", :action => "unfollow",:id => startup.id},  :method=>:post,:class=>"btn btn-primary btn-large btn-block" %>
  <% else %>
   <%= button_to 'Follow', {:controller => "startups", :action => "follow",:id => startup.id},  :method=>:post,:class=>"btn btn-primary btn-large btn-block" %>
<% end %>
<% else %>
<%= link_to 'Know More',startup,:class=>"btn btn-primary btn-large btn-block" %>
<% end %>

          </div>
        </div>

<% end %>
        
      </div> <!-- /tiles -->
  </div>
<%= will_paginate @startups %>
</div>

mashup/app/views/students/new.html.erb
<% provide(:title, 'Sign up') %>
<% if lcurrent_user %>
<div class="container">
    <div class="page-header">
      <h4>Sign up</h4>
    </div>

<div class="field col-md-5">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

      <%= f.label :fname,"First Name" %>
      <%= f.text_field :fname,:value => lcurrent_user['firstName'],:class=>"form-control" %>

      <%= f.label :lname,"Last Name" %>
      <%= f.text_field :lname,:value => lcurrent_user['lastName'],:class=>"form-control" %>

      <%= f.label :email %>
      <%= f.text_field :email,:class=>"form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password,:class=>"form-control" %>

      <%= f.label :password_confirmation, "Re-enter Password" %>
      <%= f.password_field :password_confirmation,:class=>"form-control" %>
      <br>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
</div>
<% else %>
<div class="container">
    <div class="page-header">
      <h4>Sign up</h4>
    </div>

<div class="field col-md-5">
    <%= form_for(@user) do |f|%>
    <%= render 'shared/error_messages' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
    </div>

      <%= f.label :fname,"First Name" %>
      <%= f.text_field :fname,:class=>"form-control" %>

      <%= f.label :lname,"Last Name" %>
      <%= f.text_field :lname,:class=>"form-control" %>

      <%= f.label :email %>
      <%= f.text_field :email,:class=>"form-control" %>

      <%= f.label :password %>
      <%= f.password_field :password,:class=>"form-control" %>

      <%= f.label :password_confirmation, "Re-enter Password" %>
      <%= f.password_field :password_confirmation,:class=>"form-control" %>
      <br>
      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
</div>
 <h4>or</h4> 
  <%=button_to "Sign Up with LinkedIn", login_path, :method => :post,class: "btn btn-large btn-primary" %>
</div>

<% end %>

mashup/app/views/students/profile.html.erb
<!-- Begin Profile -->
<div class="pro-details">
<div class=" ">
  <div align="center">
    <% if @user.pic_file_name %>
                <%= image_tag @user.pic.url(:thumb) %><br><br>
            <% else %>
                 <%= image_tag("profile.jpg") %><br><br> 
           <% end %>
    <h2><%= @user.fname %>&nbsp<%= @user.lname %></h2>
     <% if @user==current_user %>
                <%= link_to 'Edit Info', edit_student_path(@user),:class=>"btn btn-lg btn-primary" %><br>
      <% end %>
  </div><br>
  <div class="well">
    <div class="row">
      <div class="col-xs-4">
        <h6>
          About        
        </h6>
        <hr>
        <div class="">
        <% if @user.bio %>
          <%= @user.bio %>
        <% else %>
           This is dummy content.Profile is not yet updated.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat.
          <% end %>
        </div>
      </div>
      <div class="col-xs-4">
        <h6>
          Education and Experience
        </h6>
        <hr>
        <div class="">
           <% if @user.education %>
          <%= @user.education %>
        <% else %>
           This is dummy content.Profile is not yet updated.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat.
          <% end %>
        </div>
      </div>
      <div class="col-xs-4">
        <h6>
          Vitals
        </h6>
        <hr>
        <div class="">
          <p>Skills: <a href="#"><%= @user.skills %></a></p>
          <p>Email: <a href="#"><%= @user.email %></a></p>
          <p>Phone: <a href="#"><%= @user.phone %></a></p>
          <p>Online Profile: <a href="<%= @user.github %>"><%= @user.github %></a></p>
          <p>Links:&nbsp&nbsp <a href="<%= @user.fb %>"><i class="fa fa-facebook"></i></a>&nbsp&nbsp&nbsp&nbsp<a href="<%= @user.google %>"><i class="fa fa-google-plus"></i></a>&nbsp&nbsp&nbsp&nbsp<a href="<%= @user.linkedin %>"><i class="fa fa-linkedin"></i></a></p>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

mashup/app/views/students/show.html.erb
<!-- Begin Profile -->
<% if @user==current_user %>
<div class="container">
<div class="page-header">
<h4>Live Feed<small> All the latest updates</small></h4>
  </div>
<% @microposts.each do |micropost| %>
  <div class="row">
    <div class="col-lg-2">
      <a href="#" class="thumbnail d-profile">
        <%  @startup=Startup.find(micropost.startup_id) %>
        <% if @startup.pic_file_name %>
         <%= image_tag(@startup.pic.url(:thumb),:class=>"news-image") %>
        <% else %>
                 <%= image_tag("logo.png",:class=>"news-image") %> 
        <% end %>
    </a>
    </div>
    <div class="col-lg-10 ">
      <h6 class="demo-panel-title"><%=link_to @startup.name,@startup %></h6>
          <div class="share mrl">
            <ul>
              <li>
                <p><%= micropost.content %></p>
              </li>
            <li><small>Posted <%= time_ago_in_words(micropost.created_at) %> ago</small></li>
            </ul>
            
          </div> <!-- /share -->
          
    </div>
   </div>
<% end %>
<%= will_paginate @microposts %>
</div>

<% else %>
<div class="pro-details">
<div class=" ">
  <div align="center">
    <% if @user.pic_file_name %>
                <%= image_tag @user.pic.url(:thumb) %><br><br>
            <% else %>
                 <%= image_tag("profile.jpg") %><br><br> 
           <% end %>
    <h2><%= @user.fname %>&nbsp<%= @user.lname %></h2>
  </div><br>
  <div class="well">
    <div class="row">
      <div class="col-xs-4">
        <h6>
          About        
        </h6>
        <hr>
        <div class="">
           <% if @user.bio %>
          <%= @user.bio %>
        <% else %>
           This is dummy content.Profile is not yet updated.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. 
          <% end %>
        </div>
      </div>
      <div class="col-xs-4">
        <h6>
          Education and Experience
        </h6>
        <hr>
        <div class="">
           <% if @user.education %>
          <%= @user.education %>
        <% else %>
           This is dummy content.Profile is not yet updated.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat.
          <% end %>
        </div>
      </div>
      <div class="col-xs-4">
        <h6>
          Vitals
        </h6>
        <hr>
        <div class="">
          <p>Skills: <a href="#"><%= @user.skills %></a></p>
          <p>Email: <a href="#"><%= @user.email %></a></p>
          <p>Phone: <a href="#"><%= @user.email %></a></p>
          <p>Online Profile: <a href="<%= @user.github %>"><%= @user.github %></a></p>
          <p>Links:&nbsp&nbsp <a href="<%= @user.fb %>"><i class="fa fa-facebook"></i></a>&nbsp&nbsp&nbsp&nbsp<a href="<%= @user.google %>"><i class="fa fa-google-plus"></i></a>&nbsp&nbsp&nbsp&nbsp<a href="<%= @user.linkedin %>"><i class="fa fa-linkedin"></i></a></p>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

<% end %>            

mashup/app/views/students/updatepwd.html.erb
<% provide(:title, "Update Password") %>
<div class="container">
    <div class="page-header">
      <h4>Update your Password</h4>
    </div>
<div class="field col-md-5">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :password %>
      <%= f.password_field :password,:class=>"form-control" %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation,:class=>"form-control" %>
      <br>
      <%= f.submit "Save changes", class: "btn btn-large btn-primary" %>
    <% end %>
</div>
</div>