mashup/config/routes.rb
Mashup::Application.routes.draw do
  
  resources :startups
  resources :startups do
    member do 
        post 'follow'
        post 'unfollow'
    end
  end

  resources :students
  resources :entrepreneurs
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]
  root 'logins#home'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/supdatepwd',  to: 'students#updatepwd',            via: 'get'
  match '/eupdatepwd',  to: 'entrepreneurs#updatepwd',            via: 'get'
  match '/sprofile',  to: 'students#profile',            via: 'get'
  match '/sfollowing',  to: 'students#following',            via: 'get'
  match '/allstartups',  to: 'startups#all',            via: 'get'
  match '/allstartups',  to: 'startups#all',            via: 'post'
  match '/allstudents',  to: 'students#all',            via: 'post'
  match '/allstudents',  to: 'students#all',            via: 'get'
  resource :login do
    member do
      get 'callback'
      get 'logout'
    end
  end

  

end

mashup/app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  helper_method :lcurrent_user

  def home
     if current_user
        redirect_to current_user
     end
  end

  def show
   if lcurrent_user
   @string=lcurrent_user['siteStandardProfileRequest']['url'].scan(/id=+(\d+)/)[0][0]
   if !@user=Users.find_by(linkedin_id: @string)
      reset_session
      flash[:alert] = "Please sign up first"
      redirect_to "/"
   elsif @user.type=="Student"
      @student=Student.find_by(linkedin_id: @string)
      sign_in(@student,"Student")
      redirect_to @student
   elsif @user.type=="Entrepreneur"
      @entrepreneur=Entrepreneur.find_by(linkedin_id: @string)
      sign_in(@entrepreneur,"Entrepreneur")
      redirect_to @entrepreneur 
   end
     elsif signed_in?
      redirect_to current_user
   end
  end

  def create
    request_token = consumer.get_request_token(:oauth_callback => callback_login_url)
    Rails.cache.write(request_token.token, request_token.secret)
    redirect_to request_token.authorize_url
  end

  def callback
    request_token = OAuth::RequestToken.new(consumer, params[:oauth_token], Rails.cache.read(params[:oauth_token]))
    access_token = request_token.get_access_token(:oauth_verifier => params[:oauth_verifier])
    session[:access_token] = access_token.token
    session[:access_token_secret] = access_token.secret
    redirect_back_or "/login"
  end

  def logout
    sign_out
    reset_session
    redirect_to "/"
  end

  private
  CONSUMER_KEY = {
    :key => "efh3x5xkpxq0",
    :secret => "BWA2xEepmqKzhBfC"
  }
  CONSUMER_OPTIONS = { :site => 'https://api.linkedin.com',
                     :authorize_path => '/uas/oauth/authorize',
                     :request_token_path => '/uas/oauth/requestToken',
                     :access_token_path => '/uas/oauth/accessToken',
 :scope => 'r_fullprofile r_emailaddress r_network', :fields => ["id", "email-address", "first-name", "last-name", "headline"] }

  def consumer
    @consumer ||= OAuth::Consumer.new( CONSUMER_KEY[:key], CONSUMER_KEY[:secret], CONSUMER_OPTIONS)
  end

  def access_token
    if session[:access_token]
      @access_token ||= OAuth::AccessToken.new(consumer, session[:access_token], session[:access_token_secret])
    end
  end

  def lcurrent_user
    if access_token
      @lcurrent_user ||= JSON.parse(access_token.get('http://api.linkedin.com/v1/people/~', 'x-li-format' => 'json').body)
      # Pick some fields
      #fields = ['first-name', 'last-name', 'headline', 'industry', 'num-connections','email-address'].join(',')

      # Make a request for JSON data
      #json_txt = access_token.get("http://api.linkedin.com/v1/people/~:(#{fields})", 'x-li-format' => 'json').body
      #@current_user ||= JSON.parse(json_txt)
    end
    @lcurrent_user
  end
end

mashup/app/helpers/logins_helper.rb
module LoginsHelper
 
 CONSUMER_KEY = {
    :key => "efh3x5xkpxq0",
    :secret => "BWA2xEepmqKzhBfC"
  }
  CONSUMER_OPTIONS = { :site => 'https://api.linkedin.com',
                     :authorize_path => '/uas/oauth/authorize',
                     :request_token_path => '/uas/oauth/requestToken',
                     :access_token_path => '/uas/oauth/accessToken' }

  def consumer
    @consumer ||= OAuth::Consumer.new( CONSUMER_KEY[:key], CONSUMER_KEY[:secret], CONSUMER_OPTIONS)
  end

  def access_token
    if session[:access_token]
      @access_token ||= OAuth::AccessToken.new(consumer, session[:access_token], session[:access_token_secret])
    end
  end

  def lcurrent_user
    if access_token
      @lcurrent_user ||= JSON.parse(access_token.get('http://api.linkedin.com/v1/people/~', 'x-li-format' => 'json').body)
    end
    @lcurrent_user
  end

end

mashup/app/views/logins/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Flat UI</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Loading Bootstrap -->
    <link href="bootstrap/css/bootstrap.css" rel="stylesheet">
    <link href="bootstrap/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Loading Flat UI -->
    <link href="css/flat-ui.css" rel="stylesheet">

    <link rel="shortcut icon" href="images/favicon.ico">
    <link rel="stylesheet" type="text/css" href="css/homepage.css">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements. All other JS at the end of file. -->
    <!--[if lt IE 9]>
      <script src="js/html5shiv.js"></script>
    <![endif]-->
  </head>
  <body>
  <!--
  <video autoplay  id="bgVideo">
    <source src="<%= asset_path("preview.webm") %>" type="video/webm">
    
  </video> -->
  <div id="navbar-full">
    <div id="navbar">
     <div class="container">
        <div class="navbar-header" style="position:relative;left:-20px">
              <a class="navbar-brand" href="#"><img src="<%= asset_path("logo_latest.png") %>" style="position:relative;width:28px;height:26px;top:-2px">&nbsp&nbspSTARTUP SPHERE</a>
        </div>
      </div>      
    </div>
  </div>
  <div class="test">
    <div class="info">
       <h2>STARTUP REVOLUTION HAS ARRIVED</h2> 
        <h4><b>COME BE A PART OF IT</b></h4>
       <button class="btn btn-primary" data-toggle="modal" data-target="#RegisterModal">Register to get Started</button>&nbsp&nbsp&nbsp&nbsp<button class="btn btn-inverse" data-toggle="modal" data-target="#LoginModal">Member's Login</button>
    </div>  
  </div>  
  <!--<div class="test2">
    <div class="info2">
       <h5>Register Here for free</h5><br><br>
       <div class="row">
           <div class="span5 well">
              <label>Enter Name</label> 
              <input class="form-control" type="text" placeholder="First Name">&nbsp&nbsp&nbsp<input class="form-control" type="text" placeholder="Last Name">
              <label>Password</label> 
              <input class="form-control" type="text" placeholder="enter username">&nbsp&nbsp&nbsp<input class="form-control" type="text" placeholder="Confirmation">
              <label>Register as</label> 
              <select class="form-control" >
                  <option>student</option>
                  <option>Entrepreneur</option>
              </select>
              <hr>
              <button class="btn btn-primary">
                  Submit
              </button>&nbsp&nbsp&nbspOr&nbsp&nbsp&nbsp<button class="btn btn-info">Sign up via linkedin</button>
              
            </div>
            <div class="span4 signup">
                <h6>As a Student</h6>
                <p><small>Connect with startups. Interact with mentors and get latest updates form the world of entrepreneurship.</small></p> 
                <br>
                <h6>As an Entrepreneur</h6>
                <p><small>Connect with students. Take a look at their skillset and hire the best ones. Also, interact with other entrepreneurs</small></p> 
            </div>
           </div>
       </div>
    </div>  
  </div> 
  --> 
  <div class="test3" align="center">
     <h6> <font color="#34495E">Wanna know more about the experience?&nbsp&nbsp </font><a href="http://celbits.org/" class="btn btn-primary">Know about other  CEL projects</a></h6> 
  </div>
  <div class="test4">
    <div class="info2">
       <h5>What does <b>Startup Sphere </b>do?</h5>
         <div class="row info3" align="center">
             <div class="col-md-3">
               <img src="<%= asset_path("Banner@2x.png") %>" class="icon">
               <p><b>Connect</b></p><br>
               <p><small>We join the right dots for you by getting the ideal co-founders, mentors and resources under one roof</small></p>  
             </div>
             <div class="col-md-3 offset1">
               <img src="<%= asset_path("Compas@2x.png") %>" class="icon">
               <p><b>Search</b></p><br>
               <p><small>Startups can search for talented interns and co-founders. We curate the information on the platform for you to hand pick from</small></p>   
             </div>
             <div class="col-md-3 offset1">
                <img src="<%= asset_path("Money@2x.png") %>" class="icon">
               <p><b>Resources and Support</b></p><br>
               <p><small>We provide startups with resources and support. Besides helping them with your basic necessities we pull the right strings to get you a perfect head start</small></p>  
             </div>

         </div>
    
  </div> 
  </div> 
  

    
      <div class="bottom-menu bottom-menu-inverse">
        <div class="container">
          <div class="row" align="center">
            A CENTER FOR ENTREPRENEURIAL LEADERSHIP, BITS PILANI Initiative

            </div>
          </div>
        </div>
      
    
    <!-- /.container -->
 <!-- Modal -->
    <div class="modal fade" id="LoginModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Login</h4>
          </div>
          <div class="modal-body">

    
            <%= form_for(:session, url: sessions_path) do |f| %>
		     <div class="form-group">
		      <%= f.label :email %>
		      <%= f.text_field :email,:class=>"form-control",:placeholder=>"Enter email" %>
		     </div>

		    <div class="form-group">
		      <%= f.label :password %>
		      <%= f.password_field :password,:class=>"form-control",:placeholder=>"Enter Password" %>
		    </div>

		      <%= f.submit "Sign in", class: "btn btn-primary" %>
		    <% end %>or

            
            
            <%=button_to "Login with LinkedIn", login_path, :method => :post,:class=>"btn btn-info" %>
            
          </div>
          
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
       
    <!-- Modal -->
    <div class="modal fade" id="RegisterModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title" id="myModalLabel">Join the Revolution Now!</h4>
          </div>
          <div class="modal-body">

            <div class="row">
              <div class="col-md-4 col-md-offset-1">
                <%= link_to 'Register as a Student',"/students/new", class: "btn btn-success" %>

              </div>
              <div class="col-md-4 col-md-offset-1">
                <%= link_to 'Register as an Entrepreneur',"/entrepreneurs/new", class: "btn btn-success" %>

              </div>
            </div>
              
            
          </div>
          
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->

  </body>
</html>

mashup/app/views/logins/new.html.erb
<h1>Login#new</h1>
<p>Find me in app/views/login/new.html.erb</p>

mashup/app/views/logins/show.html.erb
<div class="container">
    <div class="page-header">
      <h4>Sign in</h4>
    </div>
<div class="field col-md-5">
<p>New user? <%= link_to "Sign up now!", root_path %></p>
    <%= form_for(:session, url: sessions_path) do |f| %>
     <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email,:class=>"form-control",:placeholder=>"Enter email" %>
    </div>
     <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password,:class=>"form-control",:placeholder=>"Enter Password" %>
    </div>
      <%= f.submit "Sign in", class: "btn btn-large btn-primary" %>
    <% end %>


<h4>or</h4>
  <%=button_to "Signin with LinkedIn", login_path, :method => :post,:class=>"btn btn-info" %>
</div>
</div>